[project]
name = "lite-llm"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = []

[project.scripts]
lite-llm = "lite_llm:main"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
